modLoader = "javafml"
license = "ARR"
issueTrackerURL = "https://github.com/Darkhax/Gilded-Sherds/issues"

[[mods]]
modId = "gildedsherds"
version = "26.1.2.0"
displayName = "GildedSherds"
updateJSONURL = "https://updates.blamejared.com/get?n=gildedsherds&gv=26.1.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/gilded-sherds"
logoFile = "logo_gildedsherds.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Potery sherds with a gilded twist! Loosely inspired by the practice of gilding and kintsugi."

[[mixins]]
config = "gildedsherds.common.mixins.json"

[[mixins]]
config = "gildedsherds.neoforge.mixins.json"

[[dependencies.gildedsherds]]
modId = "minecraft"
type = "required"
versionRange = "26.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.gildedsherds]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

